metricbeat.config.modules:
  path: ${path.config}/conf.d/*.yml
  reload.period: 10s
  reload.enabled: false
metricbeat.max_start_delay: 10s
#==========================  Modules configuration ============================
metricbeat.modules:
- module: system
  metricsets:
    - cpu             # CPU usage
    - filesystem      # File system usage for each mountpoint
    - fsstat          # File system summary metrics
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - socket         # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']
  cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
  core.metrics: ["percentages"]  # The other available option is ticks.

#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

#------------------------------- MongoDB Module ------------------------------
#- module: mongodb
#  metricsets: ["dbstats", "status"]
#  period: 10s

#  # The hosts must be passed as MongoDB URLs in the format:
#  # [mongodb://][user:pass@]host[:port].
#  # The username and password can also be set using the respective configuration
#  # options. The credentials in the URL take precedence over the username and
#  # password configuration options.
#  hosts: ["localhost:27017"]

#  # Username to use when connecting to MongoDB. Empty by default.
#  #username: user

#  # Password to use when connecting to MongoDB. Empty by default.
#  #password: pass

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
#  hosts: ["localhost:9200"]
  hosts: ["${ES_HOST}"]
  ssl.verification_mode: none
